import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { useState } from "react";
import axios from "axios";

export default function Home() {
  const [inputValue, setInputValue] = useState("");
  const [responseData, setResponseData] = useState(null);

  const handleSubmit = async (event) => {
    event.preventDefault();
    const msg = [{ role: "user", content: inputValue }];

    try {
      const response = await axios.post(
        "https://api.openai.com/v1/chat/completions",
        {
          model: "gpt-3.5-turbo",
          messages: msg,
        },
        {
          headers: {
            "Content-Type": "application/json",
            Authorization: `Bearer ${process.env.NEXT_PUBLIC_OPENAI_API_KEY}`,
          },
        }
      );
      setResponseData(response.data.choices[0].message.content);
    } catch (error) {
      console.error(error);
    }
  };

  return (
    <>
      <Head>
        <title>Chat</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className="flex flex-wrap items-center gap-[15px] px-5">
          <form onSubmit={handleSubmit}>
            <label
              className="text-[15px] font-medium leading-[35px]"
              htmlFor="input"
            >
              Ask:
            </label>
            <input
              className="mx-4"
              id="input"
              type="text"
              value={inputValue}
              onChange={(event) => setInputValue(event.target.value)}
            />
            <button
              class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"
              type="submit"
            >
              Submit
            </button>
          </form>
          {responseData && (
            <div>
              <p>Response from API:</p>
              <div>{JSON.stringify(responseData, null, 2)}</div>
            </div>
          )}
        </div>
      </main>
    </>
  );
}
